source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'YWXiMaLaYa' do
inhibit_all_warnings!

pod ‘Masonry’
pod ‘AFNetworking’
pod ‘MJExtension’
pod ‘WMPageController’
pod ‘MJRefresh’
pod ‘BlocksKit’
pod ‘MBProgressHUD’

end
